const musicContainer = document.querySelector(".music-container")
const playBtn = document.querySelector("#play")
const prevBtn = document.querySelector("#prev")
const nexBtn = document.querySelector("#next")
const audio = document.querySelector("#audio")
const musicContainer = document.querySelector(".music-container")
const musicContainer = document.querySelector(".music-container")